# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('categoryid', models.CharField(max_length=10)),
                ('brandname', models.CharField(max_length=20)),
                ('img1', models.CharField(max_length=10)),
                ('childcid_1', models.CharField(max_length=10)),
                ('productid_1', models.CharField(max_length=10)),
                ('longname1', models.CharField(max_length=50)),
                ('price1', models.CharField(max_length=10)),
                ('marketprice1', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='mustbuy',
            old_name='track',
            new_name='trackid',
        ),
        migrations.RenameField(
            model_name='nav',
            old_name='track',
            new_name='trackid',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='track',
            new_name='trackid',
        ),
        migrations.RenameField(
            model_name='wheel',
            old_name='track',
            new_name='trackid',
        ),
    ]
