# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-17 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_auto_20200617_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='childcid_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='childcid_3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='img2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='img3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='longname2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='longname3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='marketprice2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='marketprice3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='price2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='price3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='productid_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='productid_3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
