# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-19 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0012_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ischose',
            new_name='isChose',
        ),
    ]
