# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0015_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=50)),
                ('productlongname', models.CharField(max_length=100)),
                ('isxf', models.NullBooleanField(default=False)),
                ('pmdesc', models.CharField(max_length=10)),
                ('specifics', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=10)),
                ('marketprice', models.FloatField(max_length=10, null=True)),
                ('categoryid', models.CharField(max_length=10)),
                ('childcid', models.CharField(max_length=10, null=True)),
                ('childcidname', models.CharField(max_length=10, null=True)),
                ('dealerid', models.CharField(max_length=10)),
                ('storenums', models.IntegerField()),
                ('productnum', models.IntegerField()),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('obj1', django.db.models.manager.Manager()),
            ],
        ),
    ]
