# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-23 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0016_auto_20200622_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='browsedorder',
            field=models.IntegerField(default=0),
        ),
    ]
