# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0017_order_browsedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='browsedorder',
            field=models.NullBooleanField(default=False),
        ),
    ]
