# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0019_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
