# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-23 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0020_favorite_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='noRepeat',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
